version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - npm install
      - npm i -g pm2
cache:
  paths:
    - "/node_modules/**/*"
artifacts:
  files:
    - "**/*"
